### ISSUE TITLE
Cannot deploy to Dockerized WLS 12.1.3 with wls-remote-12.1.2

### ISSUE THREAD

**Issue by kubamarchwicki** [arquillian/arquillian-container-wls#21]
Hi, 
I'm using a dockerized container of WLS 12.1.3 (and 12.1.3.Update1 - as well). 
I'm forwarding the ports (all 7001,7002, 5556) locally, with the adminUrl configured to  t3://localhost:7001

When trying to deploy remotly with wls-arquillian container I'm getting following issue:
```
Caused by: javax.management.RuntimeMBeanException: java.lang.RuntimeException: [Deployer:149003]Unable to access application source information in "/tmp/arquillian8498387856032123820322fc0fb-fe90-47f0-a083-2ca4c3ddad3a.war/322fc0fb-fe90-47f0-a083-2ca4c3ddad3a.war" for application "322fc0fb-fe90-47f0-a083-2ca4c3ddad3a". The specific error is: No application files exist.
	at weblogic.utils.StackTraceDisabled.unknownMethod()
Caused by: java.lang.RuntimeException: [Deployer:149003]Unable to access application source information in "/tmp/arquillian8498387856032123820322fc0fb-fe90-47f0-a083-2ca4c3ddad3a.war/322fc0fb-fe90-47f0-a083-2ca4c3ddad3a.war" for application "322fc0fb-fe90-47f0-a083-2ca4c3ddad3a". The specific error is: No application files exist.
```

The wls log stack looks like this: 
```
<May 3, 2015 7:45:28 PM GMT> <Warning> <Deployer> <BEA-149003> <Unable to access application source information in "/tmp/arquillian8498387856032123820322fc0fb-fe90-47f0-a083-2ca4c3ddad3a.war/322fc0fb-fe90-47f0-a083-2ca4c3ddad3a.war" for application "322fc0fb-fe90-47f0-a083-2ca4c3ddad3a". The specific error is: No application files exist.> 
<May 3, 2015 7:45:28 PM GMT> <Warning> <Deployer> <BEA-149124> <Failures were detected while initiating deploy task for application "322fc0fb-fe90-47f0-a083-2ca4c3ddad3a". Error is: "[Deployer:149003]Unable to access application source information in "/tmp/arquillian8498387856032123820322fc0fb-fe90-47f0-a083-2ca4c3ddad3a.war/322fc0fb-fe90-47f0-a083-2ca4c3ddad3a.war" for application "322fc0fb-fe90-47f0-a083-2ca4c3ddad3a". The specific error is: No application files exist."> 
<May 3, 2015 7:45:28 PM GMT> <Warning> <RMI> <BEA-080003> <A RuntimeException was generated by the RMI server: javax.management.remote.rmi.RMIConnectionImpl.invoke(Ljavax.management.ObjectName;Ljava.lang.String;Ljava.rmi.MarshalledObject;[Ljava.lang.String;Ljavax.security.auth.Subject;)
 javax.management.RuntimeMBeanException: java.lang.RuntimeException: [Deployer:149003]Unable to access application source information in "/tmp/arquillian8498387856032123820322fc0fb-fe90-47f0-a083-2ca4c3ddad3a.war/322fc0fb-fe90-47f0-a083-2ca4c3ddad3a.war" for application "322fc0fb-fe90-47f0-a083-2ca4c3ddad3a". The specific error is: No application files exist..
javax.management.RuntimeMBeanException: java.lang.RuntimeException: [Deployer:149003]Unable to access application source information in "/tmp/arquillian8498387856032123820322fc0fb-fe90-47f0-a083-2ca4c3ddad3a.war/322fc0fb-fe90-47f0-a083-2ca4c3ddad3a.war" for application "322fc0fb-fe90-47f0-a083-2ca4c3ddad3a". The specific error is: No application files exist.
	at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.rethrow(DefaultMBeanServerInterceptor.java:839)
	at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.rethrowMaybeMBeanException(DefaultMBeanServerInterceptor.java:852)
	at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.invoke(DefaultMBeanServerInterceptor.java:821)
	at com.sun.jmx.mbeanserver.JmxMBeanServer.invoke(JmxMBeanServer.java:801)
	at weblogic.management.mbeanservers.domainruntime.internal.FederatedMBeanServerInterceptor.invoke(FederatedMBeanServerInterceptor.java:377)
	Truncated. see log file for complete stacktrace
Caused By: java.lang.RuntimeException: [Deployer:149003]Unable to access application source information in "/tmp/arquillian8498387856032123820322fc0fb-fe90-47f0-a083-2ca4c3ddad3a.war/322fc0fb-fe90-47f0-a083-2ca4c3ddad3a.war" for application "322fc0fb-fe90-47f0-a083-2ca4c3ddad3a". The specific error is: No application files exist.
	at weblogic.deploy.internal.adminserver.operations.OperationHelper.validateSource(OperationHelper.java:357)
	at weblogic.deploy.internal.adminserver.operations.OperationHelper.getArchiveVersionIdFromSource(OperationHelper.java:167)
	at weblogic.deploy.internal.adminserver.operations.OperationHelper.getAndValidateVersionIdWithSrc(OperationHelper.java:205)
	at weblogic.deploy.internal.adminserver.operations.ActivateOperation.updateConfiguration(ActivateOperation.java:50)
	at weblogic.deploy.internal.adminserver.operations.DeployOperation.updateConfiguration(DeployOperation.java:106)
	Truncated. see log file for complete stacktrace
> 
<May 3, 2015 7:45:28 PM GMT> <Warning> <RMI> <BEA-080003> <A RuntimeException was generated by the RMI server: javax.management.remote.rmi.RMIConnectionImpl.invoke(Ljavax.management.ObjectName;Ljava.lang.String;Ljava.rmi.MarshalledObject;[Ljava.lang.String;Ljavax.security.auth.Subject;)
 javax.management.RuntimeOperationsException.
javax.management.RuntimeOperationsException
	at javax.management.remote.rmi.RMIConnectionImpl.checkNonNull(RMIConnectionImpl.java:1665)
	at javax.management.remote.rmi.RMIConnectionImpl.invoke(RMIConnectionImpl.java:800)
	at javax.management.remote.rmi.RMIConnectionImpl_WLSkel.invoke(Unknown Source)
	at weblogic.rmi.internal.BasicServerRef.invoke(BasicServerRef.java:701)
	at weblogic.rmi.internal.BasicServerRef$1.run(BasicServerRef.java:527)
	Truncated. see log file for complete stacktrace
Caused By: java.lang.IllegalArgumentException: ObjectName must not be null
	at javax.management.remote.rmi.RMIConnectionImpl.checkNonNull(RMIConnectionImpl.java:1663)
	at javax.management.remote.rmi.RMIConnectionImpl.invoke(RMIConnectionImpl.java:800)
	at javax.management.remote.rmi.RMIConnectionImpl_WLSkel.invoke(Unknown Source)
	at weblogic.rmi.internal.BasicServerRef.invoke(BasicServerRef.java:701)
	at weblogic.rmi.internal.BasicServerRef$1.run(BasicServerRef.java:527)
	Truncated. see log file for complete stacktrace
```

I'm using https://github.com/javaee-samples/javaee7-samples/pull/301 as a reference 
wls-remote-12.1 works fine. 

Any hint? Have any of you come across smth similar? Or should I just forget about this whole Docker thing ;-)

Many thanks
--Kuba

**Comment by VineetReynolds** [comment]
Ok, I haven't tried this with WLS. Maybe someone else has. I could verify if the behavior is a bug. Are you using the WLS Docker image built from this repo - https://github.com/oracle/docker ?

**Comment by kubamarchwicki** [comment]
To be precise I'm using this https://github.com/weblogic-community/weblogic-docker/tree/attic (but that's pretty much the same) - yes that's an offical oracle docker build

**Comment by kubamarchwicki** [comment]
The referenced `javaee-samples` discussion sound relevant: https://github.com/javaee-samples/javaee7-samples/pull/301#issuecomment-99727379 and maybe gives some additional clues

**Comment by pzampino** [comment]
You should be able to use the new remote REST adapter (wls-remote-rest) in 1.0.0.Final to work with WLS in a Docker container. Note that you may have to explicitly enable the REST management API support in 12.1.3 for this to work.

**Comment by kubamarchwicki** [comment]
Hi there,
sorry for keeping that opened for a while, it didn't get back to that one for a while. Yes, `wls-remote-rest` did the job and indeed I had to enable REST management API.

My configuration snippet in Maven looked like so (for reference)

```xml
<profile>
    <id>weblogic-remote-arquillian</id>

    <properties>
        <!-- Default username/password that instructions in README.md ask to use 
            when starting up WebLogic for the first time. Note that WebLogic does not 
            have any default username/password of its own. -->
        <weblogicRemoteArquillian_adminUserName>admin</weblogicRemoteArquillian_adminUserName>
        <weblogicRemoteArquillian_adminPassword>admin007</weblogicRemoteArquillian_adminPassword>

        <!-- Default host and port when running WLS locally -->
        <weblogicRemoteArquillian_adminUrl>http://localhost:7001</weblogicRemoteArquillian_adminUrl>

        <!-- Default target after having installed developer zip distribution for 
            WebLogic -->
        <weblogicRemoteArquillian_target>myserver</weblogicRemoteArquillian_target>
    </properties>

    <dependencies>
        <dependency>
            <groupId>org.jboss.arquillian.container</groupId>
            <artifactId>arquillian-wls-remote-rest</artifactId>
            <version>1.0.1.Final</version>
            <scope>test</scope>                    
        </dependency>
        <dependency>
           <groupId>org.glassfish.jersey.core</groupId>
           <artifactId>jersey-client</artifactId>
           <version>2.15</version>
           <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.glassfish.jersey.media</groupId>
            <artifactId>jersey-media-json-processing</artifactId>
            <version>2.15</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.glassfish.jersey.media</groupId>
            <artifactId>jersey-media-multipart</artifactId>
            <version>2.15</version>
            <scope>test</scope>                
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <artifactId>maven-surefire-plugin</artifactId>
                <configuration>
                    <systemPropertyVariables>
                        <arquillian.launch>weblogic-remote-arquillian</arquillian.launch>
                        <adminUrl>${weblogicRemoteArquillian_adminUrl}</adminUrl>
                        <adminUserName>${weblogicRemoteArquillian_adminUserName}</adminUserName>
                        <adminPassword>${weblogicRemoteArquillian_adminPassword}</adminPassword>
                        <target>${weblogicRemoteArquillian_target}</target>
                    </systemPropertyVariables>
                </configuration>
            </plugin>
        </plugins>
    </build>
</profile>
```

Now I just need to figure out how to enable the REST management API upon building the docker image - but that's a different story. Anyhow - I'm closing it now. Thanks

**Comment by kubamarchwicki** [comment]
I'm only getting an exception in WebLogic logs upon undeploy but that doesn't impact the tests. I haven't drilled down that exception

```<Feb 10, 2016 4:52:14 PM GMT> <Error> <management-services-webapp> <BEA-2159602> <Management services encountered the following error: null for uri: http://172.17.0.2:7001/management/weblogic/latest/domainRuntime/deploymentManager/purgeCompletedDeploymentProgressObjects>```

**Comment by attrobit** [comment]
@pzampino Why is it not possible to execute arquillian with "wls-remote-12.1.x" over t3 with docker? Is there no solution other than using the rest management api?

**Comment by pzampino** [comment]
org.jboss.arquillian.container:arquillian-wls-remote-rest is provided for
this purpose. You shouldn't have to interact with the REST management API
directly.
