### ISSUE TITLE
arquillian-wls-remote-rest connector - purge completed deployment step fails 

### ISSUE THREAD

**Issue by garcimouche** [arquillian/arquillian-container-wls#29]
##### Issue Overview

Tests passes successfully however the `Purging Completed Deployment` step fails using arquillian-wls-remote-rest connector

##### Expected Behaviour

No Error should be displayed on weblogic server console when the app is undeployed

##### Current Behaviour

com.sun.jersey.api.NotFoundException: null for uri: http://localhost:8001/management/weblogic/latest/domainRuntime/deploymentManager/purgeCompletedDeploymentProgressObjects
	at com.sun.jersey.server.impl.application.WebApplicationImpl._handleRequest(WebApplicationImpl.java:1543)
	at com.sun.jersey.server.impl.application.WebApplicationImpl._handleRequest(WebApplicationImpl.java:1473)

##### Steps To Reproduce
1. [step 1]
2. [step 2]

##### Additional Information

Running in a Docker Container with official Oracle images

```
<details>
wls: 12.1.3.0.0
 Java version: 1.8.0_112-b15, vendor: Oracle Corporation
 Default locale: en_US, platform encoding: UTF-8
 OS name: Linux wlsadmin 4.4.0-53-generic #74-Ubuntu SMP Fri Dec 2 15:59:10 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
</details>
```

**Comment by garcimouche** [comment]
everything is working perfectly with v 12.2.1.2 of WLS.
