### ISSUE TITLE
How to config weblogic.Deployer javaVmArguments?

### ISSUE THREAD

**Issue by sylvietseng** [arquillian/arquillian-container-wls#30]
I used wls-remote-10.3.x to deploy war to remote weblogic server and got this error: `weblogic.deploy.api.tools.deployer.DeployerException: Java heap space`
This error could be solved by adding jvm arguments`-Xms256m -Xmx512m`，and the full cmd is such as: `java -Xms256m -Xmx512m -cp /bea/wlserver_10.3/server/lib/weblogic.jar weblogic.Deployer -adminurl ..................`
I've tried this command and it worked, but I couldn't find a way to config jvm arguments in this plugin.

the full log trace:
```
weblogic.deploy.api.tools.deployer.DeployerException: Java heap space
	at weblogic.deploy.api.tools.deployer.Jsr88Operation.postExecute(Jsr88Operation.java:564)
	at weblogic.deploy.api.tools.deployer.DeployOperation.execute(DeployOperation.java:49)
	at weblogic.deploy.api.tools.deployer.Deployer.perform(Deployer.java:139)
	at weblogic.deploy.api.tools.deployer.Deployer.runBody(Deployer.java:88)
	at weblogic.utils.compiler.Tool.run(Tool.java:158)
	at weblogic.utils.compiler.Tool.run(Tool.java:115)
	at weblogic.Deployer.run(Deployer.java:70)
	at weblogic.Deployer.main(Deployer.java:54)
Caused by: java.lang.OutOfMemoryError: Java heap space
	at weblogic.utils.io.UnsyncByteArrayOutputStream.resizeBuffer(UnsyncByteArrayOutputStream.java:59)
	at weblogic.utils.io.UnsyncByteArrayOutputStream.write(UnsyncByteArrayOutputStream.java:89)
	at java.io.DataOutputStream.write(DataOutputStream.java:107)
	at weblogic.deploy.api.internal.utils.JMXDeployerHelper.transferData(JMXDeployerHelper.java:754)
	at weblogic.deploy.api.internal.utils.JMXDeployerHelper.uploadSource(JMXDeployerHelper.java:650)
	at weblogic.deploy.api.spi.deploy.internal.ServerConnectionImpl.upload(ServerConnectionImpl.java:844)
	at weblogic.deploy.api.spi.deploy.internal.BasicOperation.uploadFiles(BasicOperation.java:327)
	at weblogic.deploy.api.spi.deploy.internal.BasicOperation.execute(BasicOperation.java:438)
	at weblogic.deploy.api.spi.deploy.internal.BasicOperation.run(BasicOperation.java:176)
	at weblogic.deploy.api.spi.deploy.WebLogicDeploymentManagerImpl.deploy(WebLogicDeploymentManagerImpl.java:386)
	at weblogic.deploy.api.tools.deployer.DeployOperation.execute(DeployOperation.java:48)
	... 6 more
```

**Comment by day2daychallenge** [comment]
I have the same problem. any suggestion?
